# Missing values

```{r}
library(tidyverse)
library(patchwork)
library(reshape2)
```


Load data
```{r}
names <- read.table(file = 'sources/names.tsv', sep = '\t', header = TRUE, fill = TRUE, na.strings = "NA")
names[names == "\\N"] <- NA

```

```{r}
# cp = 0 for counts, 1 for percents
missing_plots <- function(data, percent = FALSE) {
  
  # Get missing patterns
  missing_patterns <- data.frame(is.na(data)) %>%
    group_by_all() %>%
    count(name = "count", sort = TRUE) %>%
    ungroup()
  
 # missing_patterns
  new_missing_patterns <- as.matrix(
    missing_patterns[1:(length(missing_patterns)-1)])
  melted <- melt(new_missing_patterns)
  a <- apply(missing_patterns[1:(length(missing_patterns)-1)], 
             1, function(y)length(y[y == TRUE]))
  a_x <- which(a == 0)
  
  # missing_patterns2
  missing_patterns2 <- missing_patterns[1:(length(missing_patterns)-1)]
  
  missing_patterns2 <- missing_patterns2 %>% 
      rownames_to_column("id") %>% 
      gather(key, value, -id) %>% 
      mutate(missing = ifelse(value == 1, "yes", "no"))
  
  missing_patterns2 <- missing_patterns2 %>% 
    mutate(missing2 = ifelse(missing == "yes", 2, 1))
  
  missing_patterns3 <- missing_patterns2 %>% 
      mutate(missing2 = ifelse(id == a_x, 0, missing2))
   
  temp_x <- length(unique(missing_patterns3$key)) / 2 + 0.5
  temp_y <- nrow(missing_patterns) - a_x + 1
  
  # main plot
  main <- ggplot(missing_patterns3, aes(x = fct_reorder(key, -missing2, mean), y = fct_rev(fct_reorder(missing_patterns3$id,as.integer(missing_patterns3$id))), 
                                        fill = as.factor(missing2))) +
    geom_tile(color="white", alpha = 0.8) +
    scale_x_discrete(label=function(x) abbreviate(x, minlength = 3)) +
    scale_fill_manual(values=c("gray60","gray80","mediumpurple1")) +
    xlab("variable") +
    ylab("missing pattern") +
    annotate("text",x = temp_x, y = temp_y, label= "complete cases", fontface = 1, color="black") +
    theme(legend.position="none", axis.line = element_line(colour = "black"))

  #Plot Upper Side
  freq <- c()
  value <- unique(melted$Var2)
  
  if (length(apply(new_missing_patterns, 2, function(y) which(y == TRUE))) == 0){
    freq <- rep(0, length(value))
  } else {
    for (i in apply(new_missing_patterns, 2, function(y) which(y == TRUE))){
      sum <- 0
      for (j in i){
        sum <- sum + missing_patterns$count[j]
        
      }
      freq <- c(freq, sum)
    }
  }
  
  if (percent) {
    total = sum(missing_patterns$count)
    freq <- (freq/total)*100
    
    demo <- data.frame(value, freq)
    col <- ggplot(demo, aes(x = reorder(value, -freq), freq)) +
      geom_bar(stat = 'identity', fill = "blue", alpha = 0.6) +
      scale_x_discrete(label=function(x) abbreviate(x, minlength = 5)) +
      ylim(0, 100) +
      xlab("") +
      ylab("% rows missing:") +
      theme(panel.border = element_rect(color = "black", fill = NA, size = 0.5))
    
  } else {
    demo <- data.frame(value, freq)
    col <- ggplot(demo, aes(x = reorder(value, -freq), freq)) +
      geom_bar(stat = 'identity', fill = "blue", alpha = 0.6) +
      scale_x_discrete(label=function(x) abbreviate(x, minlength = 5)) +
      xlab("") +
      ylab("num rows missing:") +
      theme(panel.border = element_rect(color = "black", fill = NA, size = 0.5))
  }
  
  # Plot Right Side
  A_x <- length(unique((melted$Var1)))
  area.color <- replicate(A_x, "blue")
  area.color[a_x] <- "darkblue"
  
  if (percent) {
    total = sum(missing_patterns$count)
    rowy <- (missing_patterns$count/total)*100
    
    row <- ggplot(missing_patterns, aes(x = unique(melted$Var1), y = rowy)) +
      geom_bar(stat = "identity", fill = area.color, alpha = 0.5) +
      coord_flip() +
      scale_x_reverse(breaks = seq(0,A_x,1)) +
      ylim(0, 100) +
      xlab("") +
      ylab("% rows") +
      theme(panel.border = element_rect(color = "black", fill = NA, size = 0.5))
  } else {
    row <- ggplot(missing_patterns, aes(x = unique(melted$Var1), y = count)) +
      geom_bar(stat = "identity", fill = area.color, alpha = 0.5) +
      coord_flip() +
      scale_x_reverse(breaks = seq(0,A_x,1)) +
      xlab("") +
      ylab("row count") +
      theme(panel.border = element_rect(color = "black", fill = NA, size = 0.5))
  }

  final_plot <- col + plot_spacer() + main + row + plot_layout(ncol = 2, 
                                                               widths = c(4, 1),
                                                               heights = c(1, 3))
  final_plot
}
```

```{r}
missing_plots(names)
```

